version: 0.2

phases:
  install:
    runtime-versions:
      corretto11
      docker: 18
    commands:
      - apt-get -y install moreutils # For using 'sponge' later
      - mvn clean install # Creates a jar file
  build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_REGION) # Login to AWS ECR
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) # Extracting first 7 characters of the commitID to use it as ImageTag
      - docker build -t $ECR_REPO:latest .
      - docker tag $ECR_REPO:latest $ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - docker push $ECR_REPO:latest # Pushing the image to AWS ECR
      - docker push $ECR_REPO:$IMAGE_TAG
      - jq '.Parameters.ImageTag = "'$IMAGE_TAG'"' config.json | sponge config.json # Changes the ImageTag value from config.json

artifacts:
  files: 
    - '**/*'

cache:
  paths:
    - '/root/.m2/**/*' # Caches maven dependencies for a quicker build